<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.14</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.zair</groupId>
	<artifactId>ddd-agent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>DDD Agent</name>
	<description>AI-powered agent that generates LinkedIn posts about Domain-Driven Design topics</description>
	<url>https://github.com/ZairBulos/ddd-agent</url>

	<properties>
		<!-- Java version -->
		<java.version>25</java.version>

		<!-- Embabel agent version -->
		<embabel-agent.version>0.3.5</embabel-agent.version>

		<!-- Spring dotenv version -->
		<spring-dotenv.version>5.1.0</spring-dotenv.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.embabel.agent</groupId>
			<artifactId>embabel-agent-starter-shell</artifactId>
			<version>${embabel-agent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.embabel.agent</groupId>
			<artifactId>embabel-agent-starter-ollama</artifactId>
			<version>${embabel-agent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.embabel.agent</groupId>
			<artifactId>embabel-agent-starter-gemini</artifactId>
			<version>${embabel-agent.version}</version>
		</dependency>
		<dependency>
			<groupId>me.paulschwarz</groupId>
			<artifactId>springboot3-dotenv</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>me.paulschwarz</groupId>
				<artifactId>spring-dotenv-bom</artifactId>
				<version>${spring-dotenv.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
